# To execute this docker-compose yml file use docker-compose -f <file_name> up
# Add the "-d" flag at the end for deattached execution
version: '2.0'
services:
  firefox:
    image: selenium/node-firefox:3.8.1-erbium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: 192.168.1.2
    networks:
      - selenium_net

  chrome:
    image: selenium/node-chrome:3.8.1-erbium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: 192.168.1.2
    networks:
      - selenium_net

  hub:
    image: selenium/hub:3.8.1-erbium
    ports:
      - "4444:4444"
    networks:
      selenium_net:
        ipv4_address: 192.168.1.2

networks:
  selenium_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "192.168.1.0/24"
          gateway: "192.168.1.1"